---
  kind: "Deployment"
  apiVersion: "extensions/v1beta1"
  metadata: 
    name: "monitor"
  spec: 
    replicas: 1
    selector: 
      matchLabels: 
        id: "monitor"
    template: 
      metadata: 
        labels: 
          id: "monitor"
      spec: 
        containers: 
          - 
            name: "monitor"
            image: "tapng-monitor"
            ports: 
              - 
                containerPort: 80
                protocol: "TCP"
            env:
              -
                name: "LOG_LEVEL"
                valueFrom: 
                  configMapKeyRef: 
                    name: "monitor"
                    key: "log-level"
            imagePullPolicy: "IfNotPresent"
        restartPolicy: "Always"
        dnsPolicy: "ClusterFirst"